twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        knp_num_items_per_page: '%env(knp_num_items_per_page)%'
    #Personalizando mensajes de error
    form_themes:
        - '/layout/form/fields.html.twig'
